prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix semapv: <https://w3id.org/semapv/vocab/>

SELECT ?p1 ?p1l ?p2 ?p2l WHERE 
{
  ?p1 semapv:crossSpeciesExactMatch ?p2 .
	?p1 rdfs:label ?p1l . 
	?p2 rdfs:label ?p2l .
}

