prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?s ?lab ?ldef WHERE 
{
?s rdfs:subClassOf* <http://purl.obolibrary.org/obo/MP_0000001> . 
OPTIONAL { ?s rdfs:label ?lab }
OPTIONAL { ?s owl:equivalentClass [ rdf:type owl:Restriction ;
owl:onProperty <http://purl.obolibrary.org/obo/BFO_0000051> ;
owl:someValuesFrom ?ldef ] . }
}
