PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?cls ?label WHERE {
  ?cls a owl:Class ;
       rdfs:label ?label .
  FILTER(STRSTARTS(STR(?cls), "http://purl.obolibrary.org/obo/UPHENO_"))
  FILTER(NOT EXISTS { ?cls owl:deprecated "true"^^xsd:boolean })
  FILTER(NOT EXISTS { ?cls rdfs:subClassOf* obo:UPHENO_0001001 })
}
ORDER BY ?cls
